sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t rmrjaiswal/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rmrjaiswal/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ca-central-1"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-ca-central-1-545362484401"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
